import {
  EntityConfig,
  OrganizationUnit,
  User,
  Plan,
  StrategicTheme,
  StrategicObjective,
  KPI,
  Initiative,
  PerformanceResult,
  JourneySetupData,
} from '../../types';

export const SAMPLE_DEMO_JOURNEY: JourneySetupData = {
  entity: {
    name: 'Al Ahsa Development Authority (AHDA)',
    nameAr: 'هيئة تطوير الأحساء',
    logo: 'crest',
    primaryColor: '#059669',
    secondaryColor: '#0f766e',
    theme: 'emerald',
    mandate:
      'Catalyzing sustainable socio-economic prosperity, preserving Al Ahsa oasis heritage, and delivering world-class civic and investment services.',
    mandateAr:
      'تحفيز الازدهار الاقتصادي والاجتماعي المستدام، والحفاظ على تراث واحة الأحساء، وتقديم خدمات تنموية واستثمارية ومجتمعية عالمية المستوى.',
    sector: 'Regional Development & Municipal Authority',
    headquarters: 'Al-Hofuf, Al Ahsa, Eastern Province, KSA',
    currency: 'SAR',
    fiscalYearStart: 'January 1',
    reviewFrequency: 'Quarterly',
    decimalPrecision: 1,
  },
  organizationUnits: [
    {
      id: 'ORG-01',
      code: 'AHDA-EXEC',
      name: 'Executive Office & Governor',
      nameAr: 'مكتب المحافظ والقيادة التنفيذية',
      parentId: null,
      managerId: 'USR-08',
      managerName: 'HE Eng. Sultan Al-Mubarak',
      status: 'active',
      order: 1,
    },
    {
      id: 'ORG-02',
      code: 'AHDA-STRAT',
      name: 'Strategy & Performance Directorate',
      nameAr: 'الإدارة العامة للاستراتيجية والأداء',
      parentId: 'ORG-01',
      managerId: 'USR-02',
      managerName: 'Saad Al-Otaibi',
      status: 'active',
      order: 2,
    },
    {
      id: 'ORG-03',
      code: 'AHDA-URBAN',
      name: 'Urban Planning & Heritage Development',
      nameAr: 'إدارة التخطيط الحضري وتطوير التراث',
      parentId: 'ORG-01',
      managerId: 'USR-04',
      managerName: 'Fahad Al-Dosari',
      status: 'active',
      order: 3,
    },
    {
      id: 'ORG-04',
      code: 'AHDA-SVC',
      name: 'Citizen Services & Community Engagement',
      nameAr: 'إدارة خدمات المستفيدين والتفاعل المجتمعي',
      parentId: 'ORG-01',
      managerId: 'USR-05',
      managerName: 'Reem Al-Qahtani',
      status: 'active',
      order: 4,
    },
    {
      id: 'ORG-05',
      code: 'AHDA-IT',
      name: 'Digital Transformation & Smart City IT',
      nameAr: 'الإدارة العامة للتحول الرقمي والمدن الذكية',
      parentId: 'ORG-01',
      managerId: 'USR-07',
      managerName: 'Khaled Al-Harthi',
      status: 'active',
      order: 5,
    },
  ],
  users: [
    {
      id: 'USR-02',
      name: 'Saad Al-Otaibi',
      nameAr: 'سعد العتيبي',
      email: 's.otaibi@test.com',
      role: 'Strategy Manager',
      departmentId: 'ORG-02',
      status: 'active',
      effectiveFrom: '2025-01-01',
      effectiveTo: '2030-12-31',
      title: 'Strategy & Performance Director',
      titleAr: 'مدير عام الاستراتيجية والأداء',
    },
    {
      id: 'USR-08',
      name: 'HE Eng. Sultan Al-Mubarak',
      nameAr: 'معالي م. سلطان المبارك',
      email: 's.mubarak@test.com',
      role: 'Executive Approver',
      departmentId: 'ORG-01',
      status: 'active',
      effectiveFrom: '2025-01-01',
      effectiveTo: '2030-12-31',
      title: 'Governor & CEO',
      titleAr: 'محافظ الهيئة والرئيس التنفيذي',
    },
    {
      id: 'USR-04',
      name: 'Fahad Al-Dosari',
      nameAr: 'فهد الدوسري',
      email: 'f.dosari@test.com',
      role: 'Department Head',
      departmentId: 'ORG-03',
      status: 'active',
      effectiveFrom: '2025-01-01',
      effectiveTo: '2030-12-31',
      title: 'Director of Urban Development',
      titleAr: 'مدير إدارة التخطيط الحضري',
    },
    {
      id: 'USR-05',
      name: 'Reem Al-Qahtani',
      nameAr: 'ريم القحطاني',
      email: 'r.qahtani@test.com',
      role: 'KPI Contributor',
      departmentId: 'ORG-04',
      status: 'active',
      effectiveFrom: '2025-01-01',
      effectiveTo: '2030-12-31',
      title: 'Services & Operations Specialist',
      titleAr: 'أخصائي العمليات والمؤشرات',
    },
    {
      id: 'USR-07',
      name: 'Khaled Al-Harthi',
      nameAr: 'خالد الحارثي',
      email: 'k.harthi@test.com',
      role: 'System Administrator',
      departmentId: 'ORG-05',
      status: 'active',
      effectiveFrom: '2025-01-01',
      effectiveTo: '2030-12-31',
      title: 'Director of Digital Transformation',
      titleAr: 'مدير التحول الرقمي والأنظمة',
    },
  ],
  plan: {
    id: 'PLAN-01',
    code: 'STR-2027-2030',
    name: 'AHDA Strategic Plan 2027-2030',
    nameAr: 'خطة هيئة تطوير الأحساء الاستراتيجية 2027-2030',
    ownerId: 'USR-02',
    orgId: 'ORG-01',
    framework: 'Balanced Scorecard (BSC)',
    horizon: '2027–2030',
    reportingFrequency: 'Quarterly',
    period: 'Q1 2027',
    reviewers: ['USR-08', 'USR-02'],
    deadlines: '2027-04-15',
    status: 'Published',
    version: 'v1.0',
    publishedAt: '2026-12-28',
    mandate:
      'Catalyzing sustainable socio-economic prosperity, preserving Al Ahsa oasis heritage, and delivering world-class civic and investment services.',
    mandateAr:
      'تحفيز الازدهار الاقتصادي والاجتماعي المستدام، والحفاظ على تراث واحة الأحساء، وتقديم خدمات تنموية واستثمارية ومجتمعية عالمية المستوى.',
    vision:
      'Al Ahsa: A premier global oasis economy and vibrant sustainable cultural sanctuary by 2030.',
    visionAr:
      'الأحساء: اقتصاد واحة رائد عالمياً ووجهة ثقافية مستدامة وحيوية بحلول 2030.',
    mission:
      'To orchestrate integrated regional development, optimize public resource utilization, and deliver seamless digital-first services through agile strategic execution.',
    missionAr:
      'قيادة التنمية الإقليمية المتكاملة، وتعظيم استثمار الموارد العامة، وتقديم خدمات رقمية ميسرة من خلال حوكمة وتنفيذ استراتيجي مرن.',
    values: [
      'Heritage Stewardship',
      'Operational Excellence',
      'Citizen Centricity',
      'Digital Innovation',
    ],
    valuesAr: [
      'استدامة التراث والواحة',
      'التميز التشغيلي',
      'محورية المستفيد والمواطن',
      'الابتكار والتحول الرقمي',
    ],
  },
  themes: [
    {
      id: 'TH-01',
      code: 'TH-ECON',
      name: 'Economic Prosperity & Heritage Tourism',
      nameAr: 'الازدهار الاقتصادي وسياحة التراث',
      description: 'Accelerate oasis private investments, eco-tourism, and agricultural value-chain vibrancy.',
      descriptionAr: 'تنمية استثمارات القطاع الخاص، السياحة البيئية، وسلاسل القيمة الزراعية والتراثية.',
    },
    {
      id: 'TH-02',
      code: 'TH-URBAN',
      name: 'Sustainable Urban Planning & Infrastructure',
      nameAr: 'التخطيط الحضري المستدام والبنية التحتية',
      description: 'Modernize civic infrastructure, public realms, and protect UNESCO world-heritage greenery.',
      descriptionAr: 'تحديث البنية التحتية الحضرية، المرافق العامة، وحماية الغطاء الأخضر المسجل باليونسكو.',
    },
    {
      id: 'TH-03',
      code: 'TH-CITIZEN',
      name: 'Citizen Satisfaction & Quality of Life',
      nameAr: 'رضا المستفيدين وجودة الحياة',
      description: 'Deliver responsive civic experiences and community wellness initiatives.',
      descriptionAr: 'تقديم خدمات حكومية رائدة ورفع مستوى الرفاهية وجودة المعيشة لأهالي الأحساء.',
    },
    {
      id: 'TH-04',
      code: 'TH-DIGITAL',
      name: 'Digital Excellence & Agile Governance',
      nameAr: 'التميز الرقمي والحوكمة المرنة',
      description: 'Power data-driven decisions, automated services, and rigorous strategic performance tracking.',
      descriptionAr: 'تمكين القرارات المبنية على البيانات، أتمتة الإجراءات، وتتبع الأداء الاستراتيجي بدقة.',
    },
  ],
  objectives: [
    {
      id: 'OBJ-P01',
      code: 'OBJ-P01',
      name: 'Accelerate Oasis Tourism, Heritage Preservation & Private Investment',
      nameAr: 'تنشيط سياحة الواحة وحفظ التراث واستقطاب الاستثمار الخاص',
      perspectiveId: 'PERSP-01',
      themeId: 'TH-01',
      departmentId: 'ORG-02',
      contributingDepartmentIds: ['ORG-03'],
      ownerId: 'USR-02',
      ownerName: 'Saad Al-Otaibi',
      weight: 30,
      description: 'Foster sustainable tourism infrastructure and heritage preservation across UNESCO oasis sites.',
      descriptionAr: 'تعزيز البنية التحتية للسياحة البيئية وحماية المواقع التاريخية في الواحة.',
      planId: 'PLAN-01',
    },
    {
      id: 'OBJ-P02',
      code: 'OBJ-P02',
      name: 'Modernize Smart Urban Infrastructure & Public Green Spaces',
      nameAr: 'تحديث البنية التحتية الحضرية وتوسيع المسطحات الخضراء الذكية',
      perspectiveId: 'PERSP-03',
      themeId: 'TH-02',
      departmentId: 'ORG-03',
      contributingDepartmentIds: ['ORG-05'],
      ownerId: 'USR-04',
      ownerName: 'Fahad Al-Dosari',
      weight: 25,
      description: 'Upgrade roads, civic amenities, drainage, and smart oasis irrigation systems.',
      descriptionAr: 'تطوير شبكات الطرق والمرافق والري الذكي في كافة مراكز المحافظة.',
      planId: 'PLAN-01',
    },
    {
      id: 'OBJ-P03',
      code: 'OBJ-P03',
      name: 'Elevate Citizen Service Satisfaction & Community Quality of Life',
      nameAr: 'رفع رضا المستفيدين عن الخدمات البلدية وجودة الحياة',
      perspectiveId: 'PERSP-02',
      themeId: 'TH-03',
      departmentId: 'ORG-04',
      contributingDepartmentIds: ['ORG-05'],
      ownerId: 'USR-05',
      ownerName: 'Reem Al-Qahtani',
      weight: 25,
      description: 'Streamline resident service journeys and expand cultural and recreational programs.',
      descriptionAr: 'تبسيط رحلة الحصول على التراخيص والخدمات ودعم الفعاليات الترفيهية والثقافية.',
      planId: 'PLAN-01',
    },
    {
      id: 'OBJ-P04',
      code: 'OBJ-P04',
      name: 'Achieve Digital Transformation, Smart City Systems & Performance Agility',
      nameAr: 'تحقيق التحول الرقمي وأنظمة المدينة الذكية والمرونة المؤسسية',
      perspectiveId: 'PERSP-04',
      themeId: 'TH-04',
      departmentId: 'ORG-05',
      contributingDepartmentIds: ['ORG-02'],
      ownerId: 'USR-07',
      ownerName: 'Khaled Al-Harthi',
      weight: 20,
      description: 'Deploy GIS digital twin, IoT sensors, and enterprise BI analytics.',
      descriptionAr: 'بناء التوأم الرقمي المكاني للمحافظة وأتمتة مؤشرات الأداء الحية.',
      planId: 'PLAN-01',
    },
  ],
  kpis: [
    {
      id: 'KPI-01',
      code: 'KPI-01',
      name: 'Restored & Activated UNESCO Heritage Sites',
      nameAr: 'عدد المواقع التراثية المسجلة المستعادة والمفعلة',
      objectiveId: 'OBJ-P01',
      departmentId: 'ORG-03',
      definition: 'Cumulative number of certified historical monuments and oasis sites open to public visitors.',
      definitionAr: 'إجمالي المواقع التاريخية والتراثية التي تم ترميمها وفتحها للزوار وفق معايير هيئة التراث.',
      unit: 'Sites',
      formula: 'Count(Restored Sites)',
      direction: 'higher',
      baseline: 6,
      baselineDate: '2026-01-01',
      target: 12,
      weight: 50,
      frequency: 'Quarterly',
      source: 'Heritage Commission & Field Inspection Logs',
      ownerId: 'USR-04',
      updaterId: 'USR-04',
      reviewerId: 'USR-02',
      aggregationMethod: 'Last Value',
      thresholds: { green: 11, amber: 9 },
      evidenceRequirement: 'Handover certification and operational activation decree',
      version: 'v1.0',
      status: 'active',
    },
    {
      id: 'KPI-02',
      code: 'KPI-02',
      name: 'Private Sector Tourism & Heritage Investment',
      nameAr: 'حجم استثمارات القطاع الخاص السياحية والتراثية',
      objectiveId: 'OBJ-P01',
      departmentId: 'ORG-02',
      definition: 'Total capital invested by private developers into hospitality, recreation, and cultural venues.',
      definitionAr: 'إجمالي رؤوس الأموال المستثمرة من القطاع الخاص في المشاريع الفندقية والترفيهية.',
      unit: 'M SAR',
      formula: 'Sum(Approved Commercial Capital)',
      direction: 'higher',
      baseline: 220,
      baselineDate: '2026-01-01',
      target: 450,
      weight: 50,
      frequency: 'Quarterly',
      source: 'Investment Directorate Registry',
      ownerId: 'USR-02',
      updaterId: 'USR-02',
      reviewerId: 'USR-08',
      aggregationMethod: 'Sum',
      thresholds: { green: 420, amber: 380 },
      evidenceRequirement: 'Signed investor agreements and bank performance guarantees',
      version: 'v1.0',
      status: 'active',
    },
    {
      id: 'KPI-03',
      code: 'KPI-03',
      name: 'Smart Urban Infrastructure & Public Realm Completion',
      nameAr: 'نسبة إنجاز مشاريع تحديث البنية التحتية والمرافق الذكية',
      objectiveId: 'OBJ-P02',
      departmentId: 'ORG-03',
      definition: 'Weighted milestone completion percentage across active civic infrastructure projects.',
      definitionAr: 'نسبة الإنجاز الموزونة لمشاريع تأهيل الطرق والمرافق والري الذكي المعتمدة.',
      unit: '%',
      formula: '(Earned Value / Budget at Completion) * 100',
      direction: 'higher',
      baseline: 55,
      baselineDate: '2026-01-01',
      target: 85,
      weight: 100,
      frequency: 'Quarterly',
      source: 'PMO Project Control Engine',
      ownerId: 'USR-04',
      updaterId: 'USR-04',
      reviewerId: 'USR-02',
      aggregationMethod: 'Average',
      thresholds: { green: 80, amber: 70 },
      evidenceRequirement: 'Supervisory consultant monthly inspection sign-off',
      version: 'v1.0',
      status: 'active',
    },
    {
      id: 'KPI-04',
      code: 'KPI-04',
      name: 'Citizen & Beneficiary Experience Satisfaction Index',
      nameAr: 'مؤشر رضا المستفيدين والمواطنين عن الخدمات',
      objectiveId: 'OBJ-P03',
      departmentId: 'ORG-04',
      definition: 'Composite satisfaction rating collected through post-transaction digital surveys.',
      definitionAr: 'المعدل العام لقياس رضا المستفيدين عبر قنوات الخدمة والمنصة الرقمية.',
      unit: '%',
      formula: '(Positive Survey Ratings / Total Responses) * 100',
      direction: 'higher',
      baseline: 74,
      baselineDate: '2026-01-01',
      target: 92,
      weight: 100,
      frequency: 'Monthly',
      source: 'Customer Experience Feedback Engine',
      ownerId: 'USR-05',
      updaterId: 'USR-05',
      reviewerId: 'USR-02',
      aggregationMethod: 'Average',
      thresholds: { green: 90, amber: 85 },
      evidenceRequirement: 'Audited quarterly CX analytics report',
      version: 'v1.0',
      status: 'active',
    },
    {
      id: 'KPI-05',
      code: 'KPI-05',
      name: 'Government Process Digitalization & Automation Rate',
      nameAr: 'نسبة أتمتة الإجراءات والخدمات الحكومية الرقمية',
      objectiveId: 'OBJ-P04',
      departmentId: 'ORG-05',
      definition: 'Percentage of end-to-end municipal and authority services delivered without in-person touchpoints.',
      definitionAr: 'نسبة الخدمات المكتملة رقمياً بالكامل دون الحاجة للمراجعة الحضورية.',
      unit: '%',
      formula: '(Automated Workflows / Total Catalogued Services) * 100',
      direction: 'higher',
      baseline: 68,
      baselineDate: '2026-01-01',
      target: 95,
      weight: 100,
      frequency: 'Quarterly',
      source: 'Enterprise Architecture & IT Portal Engine',
      ownerId: 'USR-07',
      updaterId: 'USR-07',
      reviewerId: 'USR-02',
      aggregationMethod: 'Last Value',
      thresholds: { green: 90, amber: 85 },
      evidenceRequirement: 'Digital Government Authority (DGA) verification certificate',
      version: 'v1.0',
      status: 'active',
    },
  ],
  initiatives: [
    {
      id: 'INI-01',
      code: 'INI-01',
      name: 'Historical Oasis & UNESCO Cultural Heritage Corridor Revitalization',
      nameAr: 'إعادة تأهيل مسار التراث الثقافي وواحة الأحساء التاريخية',
      description: 'Comprehensive restoration of heritage sites, heritage walking circuits, and tourist visitor centers.',
      descriptionAr: 'ترميم وتطوير المعالم التاريخية ومسارات المشاة السياحية ومراكز استقبال الزوار في الواحة.',
      objectiveId: 'OBJ-P01',
      departmentId: 'ORG-03',
      sponsorId: 'USR-08',
      ownerId: 'USR-02',
      startDate: '2027-01-15',
      endDate: '2029-06-30',
      budget: 65000000,
      actualCost: 24500000,
      progress: 42,
      status: 'In Progress',
      scope: 'Restoration of key UNESCO heritage circuits and visitor amenities.',
      dependencies: 'Archaeological survey and zoning approvals.',
      risks: 'Archaeological clearance delays; Supply chain lead time for authentic restoration stone.',
      benefitKpiIds: ['KPI-01', 'KPI-02'],
      expectedOutcomes: 'Attract 1.2M annual regional visitors and generate 850 heritage hospitality jobs.',
      milestones: [
        { id: 'M-01', name: 'Schematic Heritage Masterplan Approved', nameAr: 'اعتماد المخطط التراثي', dueDate: '2027-03-31', completed: true, weight: 30 },
        { id: 'M-02', name: 'Restoration Phase 1 Contractor Mobilized', nameAr: 'بدء مقاول المرحلة الأولى', dueDate: '2027-08-30', completed: false, weight: 40 },
        { id: 'M-03', name: 'Visitor Center & Augmented Oasis Tour Live', nameAr: 'افتتاح مركز الزوار والجولة', dueDate: '2028-04-15', completed: false, weight: 30 },
      ],
    },
    {
      id: 'INI-02',
      code: 'INI-02',
      name: 'Smart Oasis Digital Twin & GIS Infrastructure Platform',
      nameAr: 'بناء التوأم الرقمي للواحة ومنصة النظم الجغرافية الذكية',
      description: 'High-resolution 3D geospatial modeling, IoT water-table monitoring, and unified municipal map.',
      descriptionAr: 'نمذجة مكانية ثلاثية الأبعاد، مجسات إنترنت الأشياء لمنسوب المياه، وخريطة بلدية موحدة.',
      objectiveId: 'OBJ-P04',
      departmentId: 'ORG-05',
      sponsorId: 'USR-08',
      ownerId: 'USR-07',
      startDate: '2027-02-01',
      endDate: '2028-11-30',
      budget: 28000000,
      actualCost: 12000000,
      progress: 58,
      status: 'In Progress',
      scope: 'Spatial data capture and integration into GIS engine.',
      dependencies: 'LiDAR flight permits and municipal boundary dataset.',
      risks: 'Inter-agency legacy data format disparities.',
      benefitKpiIds: ['KPI-05'],
      expectedOutcomes: 'Enable 100% digital building permits and automated infrastructure maintenance dispatch.',
      milestones: [
        { id: 'M-04', name: 'Aerial LiDAR Scanning & Orthophoto Capture', nameAr: 'المسح الجوي بالليدار', dueDate: '2027-05-15', completed: true, weight: 50 },
        { id: 'M-05', name: 'GIS Data Layer Integration & Spatial Engine', nameAr: 'دمج طبقات البيانات الجغرافية', dueDate: '2027-10-31', completed: false, weight: 50 },
      ],
    },
    {
      id: 'INI-03',
      code: 'INI-03',
      name: 'Unified Beneficiary Experience Portal ("Mubashir Al Ahsa")',
      nameAr: 'منصة تجربة المستفيد الموحدة (مباشر الأحساء)',
      description: 'Single-window mobile and web portal unifying municipal permits, investor concierge, and civic requests.',
      descriptionAr: 'نافذة موحدة وتطبيق ذكي للخدمات البلدية وتراخيص المستثمرين والشكاوى الفورية.',
      objectiveId: 'OBJ-P03',
      departmentId: 'ORG-04',
      sponsorId: 'USR-08',
      ownerId: 'USR-05',
      startDate: '2027-01-01',
      endDate: '2027-12-31',
      budget: 18500000,
      actualCost: 14200000,
      progress: 76,
      status: 'In Progress',
      scope: 'Unified citizen portal frontend, payment rails, and customer CRM.',
      dependencies: 'Nafath SSO identity federation.',
      risks: 'Integration dependencies with legacy backend billing APIs.',
      benefitKpiIds: ['KPI-04'],
      expectedOutcomes: 'Reduce service SLA from 14 business days to under 4 hours.',
      milestones: [
        { id: 'M-06', name: 'Unified Design System & Service Journey Blueprints', nameAr: 'نظام التصميم ومسارات الخدمة', dueDate: '2027-03-31', completed: true, weight: 50 },
        { id: 'M-07', name: 'Payment Gateway & Nafath SSO Production Integration', nameAr: 'بوابة الدفع والربط مع نفاذ', dueDate: '2027-07-31', completed: false, weight: 50 },
      ],
    },
    {
      id: 'INI-04',
      code: 'INI-04',
      name: 'Green Oasis Belt Preservation & Smart Irrigation Network',
      nameAr: 'حزام الواحة الخضراء وشبكة الري وإعادة التدوير الذكية',
      description: 'Installing sensor-controlled recycled water distribution networks to safeguard 2.5M palm trees.',
      descriptionAr: 'تمديد شبكات المياه المعالجة الذكية لحماية 2.5 مليون نخلة ومكافحة التصحر.',
      objectiveId: 'OBJ-P02',
      departmentId: 'ORG-03',
      sponsorId: 'USR-08',
      ownerId: 'USR-04',
      startDate: '2027-04-01',
      endDate: '2030-03-31',
      budget: 42000000,
      actualCost: 5000000,
      progress: 18,
      status: 'Planned',
      scope: 'Tertiary effluent water network and smart IoT pressure valves.',
      dependencies: 'Ministry of Environment and Water right-of-way easement.',
      risks: 'Right-of-way permissions across rural agricultural corridors.',
      benefitKpiIds: ['KPI-03'],
      expectedOutcomes: 'Save 35% potable groundwater consumption and expand green canopy by 15%.',
      milestones: [
        { id: 'M-08', name: 'Hydraulic Model & Network Engineering Design', nameAr: 'المخطط الهيدروليكي والتصميم', dueDate: '2027-09-30', completed: false, weight: 100 },
      ],
    },
  ],
  results: [
    {
      id: 'RES-01',
      kpiId: 'KPI-01',
      period: 'Q1 2027',
      year: 2027,
      quarter: 'Q1',
      target: 12,
      actual: 10,
      status: 'Approved',
      submittedBy: 'USR-04',
      submittedAt: '2027-04-02',
      reviewedBy: 'USR-02',
      reviewedAt: '2027-04-04',
      evidenceTitle: 'Heritage Commission handover decree',
      evidenceSummary: '10 sites fully opened; 2 sites undergoing final municipal safety certification.',
      version: 1,
      history: [],
    },
    {
      id: 'RES-02',
      kpiId: 'KPI-02',
      period: 'Q1 2027',
      year: 2027,
      quarter: 'Q1',
      target: 450,
      actual: 410,
      status: 'Approved',
      submittedBy: 'USR-02',
      submittedAt: '2027-04-03',
      reviewedBy: 'USR-08',
      reviewedAt: '2027-04-04',
      evidenceTitle: 'Private investment agreements registry',
      evidenceSummary: 'SAR 410M committed; signed luxury eco-resort deal at Al-Asfar Lake.',
      version: 1,
      history: [],
    },
    {
      id: 'RES-03',
      kpiId: 'KPI-03',
      period: 'Q1 2027',
      year: 2027,
      quarter: 'Q1',
      target: 85,
      actual: 78,
      status: 'Approved',
      submittedBy: 'USR-04',
      submittedAt: '2027-04-02',
      reviewedBy: 'USR-02',
      reviewedAt: '2027-04-04',
      evidenceTitle: 'Supervisory consultant monthly inspection sign-off',
      evidenceSummary: 'Infrastructure delivery at 78% due to asphalt supply scheduling.',
      version: 1,
      history: [],
    },
    {
      id: 'RES-04',
      kpiId: 'KPI-04',
      period: 'Q1 2027',
      year: 2027,
      quarter: 'Q1',
      target: 92,
      actual: 88.5,
      status: 'Approved',
      submittedBy: 'USR-05',
      submittedAt: '2027-04-01',
      reviewedBy: 'USR-02',
      reviewedAt: '2027-04-03',
      evidenceTitle: 'Beneficiary satisfaction survey data export',
      evidenceSummary: 'Satisfaction rose from 74% to 88.5% with launch of digital permit services.',
      version: 1,
      history: [],
    },
    {
      id: 'RES-05',
      kpiId: 'KPI-05',
      period: 'Q1 2027',
      year: 2027,
      quarter: 'Q1',
      target: 95,
      actual: 91,
      status: 'Approved',
      submittedBy: 'USR-07',
      submittedAt: '2027-04-02',
      reviewedBy: 'USR-02',
      reviewedAt: '2027-04-04',
      evidenceTitle: 'Digital transformation audit report',
      evidenceSummary: '91% services digitized; remaining 9% involve notary legal verification.',
      version: 1,
      history: [],
    },
  ],
};

// AI Suggestion Engine for Objectives & Initiatives (MOM Section 10)
export interface AiObjectiveRecommendation {
  suggestedKpis: Array<{
    name: string;
    unit: string;
    formula: string;
    target: number;
    baseline: number;
    frequency: 'Quarterly' | 'Monthly';
    description: string;
  }>;
  suggestedInitiatives: Array<{
    name: string;
    description: string;
    budget: number;
    timeline: string;
    status: 'Planned' | 'In Progress';
  }>;
}

export function generateAiSuggestionsForObjective(objectiveTitle: string): AiObjectiveRecommendation {
  const title = (objectiveTitle || '').toLowerCase();

  if (title.includes('tourism') || title.includes('heritage') || title.includes('invest') || title.includes('تراث') || title.includes('سياح')) {
    return {
      suggestedKpis: [
        {
          name: 'Annual Heritage Tourism Inflow & Overnight Stays',
          unit: 'Visitors',
          formula: 'Sum(Hospitality Registrations)',
          target: 1200000,
          baseline: 750000,
          frequency: 'Quarterly',
          description: 'Measure the year-over-year increase in verified cultural tourist visitors.',
        },
        {
          name: 'Private Hospitality Capital Mobilization Rate',
          unit: 'M SAR',
          formula: 'Sum(Foreign & Local Private Direct Investment)',
          target: 600,
          baseline: 280,
          frequency: 'Quarterly',
          description: 'Volume of commercial agreements executed for boutique oasis hotels and dining.',
        },
      ],
      suggestedInitiatives: [
        {
          name: 'UNESCO Oasis Culinary & Artisan Crafts Incubator',
          description: 'Establish public-private incubators supporting regional date farming, handicrafts, and heritage hospitality.',
          budget: 16000000,
          timeline: '2027–2029',
          status: 'Planned',
        },
        {
          name: 'Al-Qaisariyah Historic Souq Digital Wayfinding & Heritage Lighting',
          description: 'Deploy pedestrian wayfinding, smart signage, and architectural facade lighting across historic bazaars.',
          budget: 12500000,
          timeline: '2027–2028',
          status: 'In Progress',
        },
      ],
    };
  }

  if (title.includes('urban') || title.includes('infra') || title.includes('green') || title.includes('حضري') || title.includes('بنية')) {
    return {
      suggestedKpis: [
        {
          name: 'Per Capita Green Canopy & Public Realm Area',
          unit: 'm²/Capita',
          formula: 'Total Public Green Area / Resident Population',
          target: 14.5,
          baseline: 8.2,
          frequency: 'Quarterly',
          description: 'Targeted green open space density per resident in compliance with Quality of Life benchmarks.',
        },
        {
          name: 'Recycled Irrigation Water Utilization Efficiency',
          unit: '%',
          formula: '(Treated Effluent Used / Total Irrigation Demand) * 100',
          target: 85,
          baseline: 42,
          frequency: 'Monthly',
          description: 'Percentage of urban landscape irrigated with treated non-potable water.',
        },
      ],
      suggestedInitiatives: [
        {
          name: 'Pedestrian Boulevard & Green Oasis Shading Corridors',
          description: 'Construct 45km of continuous shaded pedestrian and cycling greenways linking historical villages.',
          budget: 34000000,
          timeline: '2027–2029',
          status: 'Planned',
        },
      ],
    };
  }

  // Default intelligent governance suggestions
  return {
    suggestedKpis: [
      {
        name: 'Strategic Milestones On-Time Completion Rate',
        unit: '%',
        formula: '(Milestones Achieved on Schedule / Total Milestones) * 100',
        target: 95,
        baseline: 72,
        frequency: 'Quarterly',
        description: 'Measures project governance rigor and execution velocity across responsible sectors.',
      },
      {
        name: 'Operational Efficiency & Expense Optimization Index',
        unit: '%',
        formula: '(Actual Operating Efficiency / Benchmark) * 100',
        target: 90,
        baseline: 78,
        frequency: 'Quarterly',
        description: 'Tracking optimization of public funds and delivery cycle times.',
      },
    ],
    suggestedInitiatives: [
      {
        name: 'Enterprise Strategic PMO & Rapid Escalation Framework',
        description: 'Deploy automated dashboarding and executive bottleneck clearance mechanisms across all authority units.',
        budget: 9500000,
        timeline: '2027–2028',
        status: 'In Progress',
      },
    ],
  };
}
